### ISSUE TITLE
Dataset

### ISSUE THREAD

**Issue by sheanps** [come880412/Scene-Text-Detection-and-Recognition#1]
Hi, thank you for your work. Do you still have dataset available? The link in your repository doesn't have the dataset you trained on.

**Comment by come880412** [comment]
Hi,
This dataset is provided by the official (https://tbrain.trendmicro.com.tw/Competitions/Details/19)
The policy shows that we cannot give you the dataset on our own.

Hope you can understand

Thanks.

**Comment by sheanps** [comment]
> Hi,
> 
> This dataset is provided by the official (https://tbrain.trendmicro.com.tw/Competitions/Details/19)
> 
> The policy shows that we cannot give you the dataset on our own.
> 
> 
> 
> Hope you can understand
> 
> 
> 
> Thanks.
> 
> 

Thank you for responding. I understand! However, I don't see a dataset in the link you have provided. 

Thanks.

**Comment by come880412** [comment]
![image](https://user-images.githubusercontent.com/59093784/209432888-45d673a3-d46b-46d5-b013-8605d36b3151.png)

On my page, I have an item "Download Dataset".
You may first register for this competition, so as to have permission to download data

Hope this helps!

Thanks!
